config/routes.rb
FamilyTree::Application.routes.draw do
  resources :relationship_types

  resources :people do
    resources :relationships
  end

  get "home/index"

  root :to => 'home#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :date_of_birth, :name

  validates :name, :presence => true
  validates :date_of_birth, allow_nil: true, format: {
    # TO DO: validate month/date in correct range
    with: /\A\d{4}(-\d{1,2}(-\d{1,2})?)?\z/
  }

  has_many :relationships, :dependent => :destroy
  has_many :reverse_relationships, :dependent => :destroy, class_name: 'Relationship', foreign_key: 'related_person_id'

  def all_relationships
    relationships | reverse_relationships
  end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :relationship_type_id, :person_id, :related_person_id

  belongs_to :relationship_type
  belongs_to :person
  belongs_to :related_person, :class_name => 'Person'

  validates :relationship_type, :person, :related_person, :presence => true
end

app/models/relationship_type.rb
class RelationshipType < ActiveRecord::Base
  attr_accessible :name, :backward_name

  has_many :relationships, :dependent => :destroy

  validates :name, :presence => true

  before_save do
    self.backward_name = nil if backward_name.blank?
  end

  def name_of_backward_relationship
    backward_name || name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.json
  def index
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/relationship_types_controller.rb
class RelationshipTypesController < ApplicationController
  # GET /relationship_types
  # GET /relationship_types.json
  def index
    @relationship_types = RelationshipType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @relationship_types }
    end
  end

  # GET /relationship_types/1
  # GET /relationship_types/1.json
  def show
    @relationship_type = RelationshipType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @relationship_type }
    end
  end

  # GET /relationship_types/new
  # GET /relationship_types/new.json
  def new
    @relationship_type = RelationshipType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @relationship_type }
    end
  end

  # GET /relationship_types/1/edit
  def edit
    @relationship_type = RelationshipType.find(params[:id])
  end

  # POST /relationship_types
  # POST /relationship_types.json
  def create
    @relationship_type = RelationshipType.new(params[:relationship_type])

    respond_to do |format|
      if @relationship_type.save
        format.html { redirect_to @relationship_type, notice: 'Relationship type was successfully created.' }
        format.json { render json: @relationship_type, status: :created, location: @relationship_type }
      else
        format.html { render action: "new" }
        format.json { render json: @relationship_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /relationship_types/1
  # PUT /relationship_types/1.json
  def update
    @relationship_type = RelationshipType.find(params[:id])

    respond_to do |format|
      if @relationship_type.update_attributes(params[:relationship_type])
        format.html { redirect_to @relationship_type, notice: 'Relationship type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @relationship_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /relationship_types/1
  # DELETE /relationship_types/1.json
  def destroy
    @relationship_type = RelationshipType.find(params[:id])
    @relationship_type.destroy

    respond_to do |format|
      format.html { redirect_to relationship_types_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_filter do
    @person = Person.find(params[:person_id])
  end

  # GET /people/1/relationships
  # GET /people/1/relationships.json
  def index
    @relationships = @person.relationships

    respond_to do |format|
      format.html # index.html.haml
      format.json { render json: @relationships }
    end
  end

  # GET /people/1/relationships/1
  # GET /people/1/relationships/1.json
  def show
    @relationship = Relationship.find(params[:id])

    respond_to do |format|
      format.html # show.html.haml
      format.json { render json: @relationship }
    end
  end

  # GET /people/1/relationships/new
  # GET /people/1/relationships/new.json
  def new
    @relationship = @person.relationships.new

    respond_to do |format|
      format.html # new.html.haml
      format.json { render json: @relationship }
    end
  end

  # GET /people/1/relationships/1/edit
  def edit
    @relationship = Relationship.find(params[:id])
  end

  # POST /people/1/relationships
  # POST /people/1/relationships.json
  def create
    @relationship = @person.relationships.new(params[:relationship])

    respond_to do |format|
      if @relationship.save
        format.html { redirect_to person_relationship_path(@person, @relationship), notice: 'Relationship was successfully created.' }
        format.json { render json: @relationship, status: :created, location: @relationship }
      else
        format.html { render action: "new" }
        format.json { render json: @relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1/relationships/1
  # PUT /people/1/relationships/1.json
  def update
    @relationship = Relationship.find(params[:id])

    respond_to do |format|
      if @relationship.update_attributes(params[:relationship])
        format.html { redirect_to person_relationship_path(@person, @relationship), notice: 'Relationship was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1/relationships/1
  # DELETE /people/1/relationships/1.json
  def destroy
    @relationship = Relationship.find(params[:id])
    @relationship.destroy

    respond_to do |format|
      format.html { redirect_to person_relationships_path(@person) }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/relationship_types_helper.rb
module RelationshipTypesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/home/index.html.haml
%h1 FamilyTree

%p This site lets you manage your family tree.

%p= link_to 'List people', people_path

%p= link_to 'List relationship types', relationship_types_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title FamilyTree
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = yield

app/views/people/_form.html.haml
= form_for @person do |f|
  -if @person.errors.any?
    #error_explanation
      %h2= "#{pluralize(@person.errors.count, "error")} prohibited this person from being saved:"
      %ul
        - @person.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :date_of_birth
    = f.text_field :date_of_birth
    YYYY or YYYY-MM or YYYY-MM-DD
  .actions
    = f.submit 'Save'

app/views/people/edit.html.haml
%h1 Editing person

= render 'form'

= link_to 'Show', @person
\|
= link_to 'Relationships', person_relationships_path(@person)
\|
= link_to 'Back', people_path

app/views/people/index.html.haml
%h1 Listing people

%table
  %tr
    %th Name
    %th Date of birth
    %th
    %th
    %th

  - @people.each do |person|
    %tr
      %td= person.name
      %td= person.date_of_birth
      %td= link_to 'Show', person
      %td= link_to 'Edit', edit_person_path(person)
      %td= link_to 'Destroy', person, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Person', new_person_path
\|
= link_to 'Back', root_url

app/views/people/new.html.haml
%h1 New person

= render 'form'

= link_to 'Back', people_path

app/views/people/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @person.name
%p
  %b Date of birth:
  = @person.date_of_birth

- @person.all_relationships.each do |rel|
  %p
    - if rel.person == @person
      %b #{rel.relationship_type.name.just_titleize}:
      = link_to rel.related_person.name, rel.related_person
    - else
      %b #{rel.relationship_type.name_of_backward_relationship.just_titleize}:
      = link_to rel.person.name, rel.person

= link_to 'Edit', edit_person_path(@person)
\|
= link_to 'New Relationship', new_person_relationship_path(@person)
\|
= link_to 'Back', people_path

app/views/relationship_types/_form.html.haml
= form_for @relationship_type do |f|
  -if @relationship_type.errors.any?
    #error_explanation
      %h2= "#{pluralize(@relationship_type.errors.count, "error")} prohibited this relationship_type from being saved:"
      %ul
        - @relationship_type.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :backward_name
    = f.text_field :backward_name
  .actions
    = f.submit 'Save'

app/views/relationship_types/edit.html.haml
%h1 Editing relationship type

= render 'form'

= link_to 'Show', @relationship_type
\|
= link_to 'Back', relationship_types_path

app/views/relationship_types/index.html.haml
%h1 Listing relationship types

%table
  %tr
    %th Name
    %th Backward name
    %th
    %th
    %th

  - @relationship_types.each do |relationship_type|
    %tr
      %td= relationship_type.name
      %td= relationship_type.read_attribute :backward_name
      %td= link_to 'Show', relationship_type
      %td= link_to 'Edit', edit_relationship_type_path(relationship_type)
      %td= link_to 'Destroy', relationship_type, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Relationship type', new_relationship_type_path
\|
= link_to 'Back', root_url

app/views/relationship_types/new.html.haml
%h1 New relationship type

= render 'form'

= link_to 'Back', relationship_types_path

app/views/relationship_types/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @relationship_type.name
%p
  %b Backward name:
  = @relationship_type.backward_name

= link_to 'Edit', edit_relationship_type_path(@relationship_type)
\|
= link_to 'Back', relationship_types_path

app/views/relationships/_form.html.haml
= form_for [@person, @relationship] do |f|
  -if @relationship.errors.any?
    #error_explanation
      %h2= "#{pluralize(@relationship.errors.count, "error")} prohibited this relationship from being saved:"
      %ul
        - @relationship.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :relationship_type_id
    = f.collection_select :relationship_type_id, RelationshipType.all, :id, :name, :include_blank => true
  .field
    = f.label :related_person_id
    = f.collection_select :related_person_id, Person.all, :id, :name, :include_blank => true
  .actions
    = f.submit 'Save'

app/views/relationships/edit.html.haml
%h1 Editing relationship for #{@person.name}

= render 'form'

= link_to 'Show', person_relationship_path(@person, @relationship)
\|
= link_to 'Back', person_relationships_path(@person)

app/views/relationships/index.html.haml
%h1 Listing relationships for #{@person.name}

%table
  %tr
    %th Relationship type
    %th Related person
    %th
    %th
    %th

  - @relationships.each do |relationship|
    %tr
      %td= relationship.relationship_type.name
      %td= relationship.related_person.name
      %td= link_to 'Show', person_relationship_path(@person, relationship)
      %td= link_to 'Edit', edit_person_relationship_path(@person, relationship)
      %td= link_to 'Destroy', person_relationship_path(@person, relationship), :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Relationship', new_person_relationship_path(@person)
\|
= link_to 'Back', edit_person_path(@person)

app/views/relationships/new.html.haml
%h1 New relationship for #{@person.name}

= render 'form'

= link_to 'Back', person_path(@person)

app/views/relationships/show.html.haml
%p#notice= notice

%p
  %b Person:
  = @relationship.person.name
%p
  %b Relationship type:
  = @relationship.relationship_type.name
%p
  %b Related person:
  = @relationship.related_person.name

= link_to 'Edit', edit_person_relationship_path(@person, @relationship)
\|
= link_to 'Back', person_relationships_path(@person)